package banque.entity;
// Generated 27 mars 2016 14:02:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Banque generated by hbm2java
 */
public class Banque  implements java.io.Serializable {


     private Short banqueId;
     private String nom;
     private String ville;
     private Set clientBanques = new HashSet(0);
     private Set personnels = new HashSet(0);

    public Banque() {
    }

	
    public Banque(String nom, String ville) {
        this.nom = nom;
        this.ville = ville;
    }
    public Banque(String nom, String ville, Set clientBanques, Set personnels) {
       this.nom = nom;
       this.ville = ville;
       this.clientBanques = clientBanques;
       this.personnels = personnels;
    }
   
    public Short getBanqueId() {
        return this.banqueId;
    }
    
    public void setBanqueId(Short banqueId) {
        this.banqueId = banqueId;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public Set getClientBanques() {
        return this.clientBanques;
    }
    
    public void setClientBanques(Set clientBanques) {
        this.clientBanques = clientBanques;
    }
    public Set getPersonnels() {
        return this.personnels;
    }
    
    public void setPersonnels(Set personnels) {
        this.personnels = personnels;
    }
}


