package banque.entity;
// Generated 27 mars 2016 14:02:36 by Hibernate Tools 4.3.1


import com.google.gson.Gson;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Banque generated by hbm2java
 */
@XmlRootElement(name="banque")
public class Banque  implements java.io.Serializable {

     private Short banqueId;
     private String nom;
     private String ville;
//     private Set clientBanques = new HashSet(0);
//     private Set personnels = new HashSet(0);

    public Banque() {
    }


    public Banque(String nom, String ville) {
        this.nom = nom;
        this.ville = ville;
    }

//    public Banque(String nom, String ville, Set clientBanques, Set personnels) {
//       this.nom = nom;
//       this.ville = ville;
//       this.clientBanques = clientBanques;
//       this.personnels = personnels;
//    }

    @XmlElement
    public Short getBanqueId() {
        return this.banqueId;
    }

    public void setBanqueId(Short banqueId) {
        this.banqueId = banqueId;
    }

    @XmlElement
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    @XmlElement
    public String getVille() {
        return this.ville;
    }

    public void setVille(String ville) {
        this.ville = ville;
    }

//    @XmlElement
//    public Set getClientBanques() {
//        return this.clientBanques;
//    }
//
//    public void setClientBanques(Set clientBanques) {
//        this.clientBanques = clientBanques;
//    }
//
//    @XmlElement
//    public Set getPersonnels() {
//        return this.personnels;
//    }
//
//    public void setPersonnels(Set personnels) {
//        this.personnels = personnels;
//    }

    public String toString() {
        Gson gson = new Gson();
        HashMap<String, String> jsonArgs = new HashMap<String, String>();
        jsonArgs.put("banqueId", getBanqueId().toString());
        jsonArgs.put("nom", getNom());
        jsonArgs.put("ville", getVille());
        return gson.toJson(jsonArgs);
    }
}


