package banque.entity;
// Generated 27 mars 2016 14:02:36 by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * CompteCourant generated by hbm2java
 */
@XmlRootElement(name="compteCourant")
public class CompteCourant  implements java.io.Serializable {

     private Short compteCourantId;
     private ClientBanque clientBanque;
     private Integer montant;
     private Boolean bloque;
     private int iban;

    public CompteCourant() {
    }


    public CompteCourant(ClientBanque clientBanque, int iban) {
        this.clientBanque = clientBanque;
        this.iban = iban;
//        this.montant = 0;
//        this.bloque = false;
    }
    public CompteCourant(ClientBanque clientBanque, Integer montant, Boolean bloque, int iban) {
       this.clientBanque = clientBanque;
       this.montant = montant;
       this.bloque = bloque;
       this.iban = iban;
    }

    @XmlElement
    public Short getCompteCourantId() {
        return this.compteCourantId;
    }

    public void setCompteCourantId(Short compteCourantId) {
        this.compteCourantId = compteCourantId;
    }

    @XmlElement
    public ClientBanque getClientBanque() {
        return this.clientBanque;
    }

    public void setClientBanque(ClientBanque clientBanque) {
        this.clientBanque = clientBanque;
    }

    @XmlElement
    public Integer getMontant() {
        return this.montant;
    }

    public void setMontant(Integer montant) {
        this.montant = montant;
    }

    @XmlElement
    public Boolean getBloque() {
        return this.bloque;
    }

    public void setBloque(Boolean bloque) {
        this.bloque = bloque;
    }

    @XmlElement
    public int getIban() {
        return this.iban;
    }

    public void setIban(int iban) {
        this.iban = iban;
    }
}


