package banque.entity;
// Generated 27 mars 2016 14:02:36 by Hibernate Tools 4.3.1

import com.google.gson.Gson;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.HashMap;

/**
 * CompteCourant generated by hbm2java
 */
@XmlRootElement(name="compteCourant")
public class CompteCourant  implements java.io.Serializable {

     private Short compteCourantId;
     private ClientBanque clientBanque;
     private float montant;
     private Boolean bloque;
     private int iban;

    public CompteCourant() {
    }


    public CompteCourant(ClientBanque clientBanque, int iban) {
        this.clientBanque = clientBanque;
        this.iban = iban;
        this.montant = 0;
        this.bloque = false;
    }
    public CompteCourant(ClientBanque clientBanque, float montant, Boolean bloque, int iban) {
       this.clientBanque = clientBanque;
       this.montant = montant;
       this.bloque = bloque;
       this.iban = iban;
    }

    @XmlElement
    public Short getCompteCourantId() {
        return this.compteCourantId;
    }

    public void setCompteCourantId(Short compteCourantId) {
        this.compteCourantId = compteCourantId;
    }

    @XmlElement
    public ClientBanque getClientBanque() {
        return this.clientBanque;
    }

    public void setClientBanque(ClientBanque clientBanque) {
        this.clientBanque = clientBanque;
    }

    @XmlElement
    public float getMontant() {
        return this.montant;
    }

    public void setMontant(float montant) {
        this.montant = montant;
    }

    @XmlElement
    public Boolean getBloque() {
        return this.bloque;
    }

    public void setBloque(Boolean bloque) {
        this.bloque = bloque;
    }

    @XmlElement
    public int getIban() {
        return this.iban;
    }

    public void setIban(int iban) {
        this.iban = iban;
    }

    public String toString() {
        Gson gson = new Gson();
        HashMap<String, String> jsonArgs = new HashMap<String, String>();
        jsonArgs.put("compteCourantId", getCompteCourantId().toString());
        jsonArgs.put("clientBanque", getClientBanque().toString());
        jsonArgs.put("montant", Float.toString(getMontant()));
        jsonArgs.put("bloque", Boolean.toString(getBloque()));
        jsonArgs.put("iban", Integer.toString(getIban()));
        return gson.toJson(jsonArgs);
    }
}


