package banque.entity;
// Generated 27 mars 2016 14:02:36 by Hibernate Tools 4.3.1



/**
 * CompteCourant generated by hbm2java
 */
public class CompteCourant  implements java.io.Serializable {


     private Short compteCourantId;
     private ClientBanque clientBanque;
     private Integer montant;
     private Boolean bloque;
     private short iban;

    public CompteCourant() {
    }

	
    public CompteCourant(ClientBanque clientBanque, short iban) {
        this.clientBanque = clientBanque;
        this.iban = iban;
    }
    public CompteCourant(ClientBanque clientBanque, Integer montant, Boolean bloque, short iban) {
       this.clientBanque = clientBanque;
       this.montant = montant;
       this.bloque = bloque;
       this.iban = iban;
    }
   
    public Short getCompteCourantId() {
        return this.compteCourantId;
    }
    
    public void setCompteCourantId(Short compteCourantId) {
        this.compteCourantId = compteCourantId;
    }
    public ClientBanque getClientBanque() {
        return this.clientBanque;
    }
    
    public void setClientBanque(ClientBanque clientBanque) {
        this.clientBanque = clientBanque;
    }
    public Integer getMontant() {
        return this.montant;
    }
    
    public void setMontant(Integer montant) {
        this.montant = montant;
    }
    public Boolean getBloque() {
        return this.bloque;
    }
    
    public void setBloque(Boolean bloque) {
        this.bloque = bloque;
    }
    public short getIban() {
        return this.iban;
    }
    
    public void setIban(short iban) {
        this.iban = iban;
    }




}


