package banque.entity;
// Generated 27 mars 2016 14:02:36 by Hibernate Tools 4.3.1


import com.google.gson.Gson;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
/**
 * Credit generated by hbm2java
 */
@XmlRootElement(name="credit")
public class Credit  implements java.io.Serializable {


     private Short creditId;
     private CompteEpargne compteEpargne;
     private float montant;
     private Short taux;
     private Date dateEmprunt;
     private short duree;

    public Credit() {
    }


    public Credit(CompteEpargne compteEpargne, Date dateEmprunt, short duree) {
        this.compteEpargne = compteEpargne;
        this.dateEmprunt = dateEmprunt;
        this.duree = duree;
    }
    public Credit(CompteEpargne compteEpargne, float montant, Short taux, Date dateEmprunt, short duree) {
       this.compteEpargne = compteEpargne;
       this.montant = montant;
       this.taux = taux;
       this.dateEmprunt = dateEmprunt;
       this.duree = duree;
    }

    @XmlElement
    public Short getCreditId() {
        return this.creditId;
    }

    public void setCreditId(Short creditId) {
        this.creditId = creditId;
    }

    @XmlElement
    public CompteEpargne getCompteEpargne() {
        return this.compteEpargne;
    }

    public void setCompteEpargne(CompteEpargne compteEpargne) {
        this.compteEpargne = compteEpargne;
    }

    @XmlElement
    public float getMontant() {
        return this.montant;
    }

    public void setMontant(float montant) {
        this.montant = montant;
    }

    @XmlElement
    public Short getTaux() {
        return this.taux;
    }

    public void setTaux(Short taux) {
        this.taux = taux;
    }

    @XmlElement
    public Date getDateEmprunt() {
        return this.dateEmprunt;
    }

    public void setDateEmprunt(Date dateEmprunt) {
        this.dateEmprunt = dateEmprunt;
    }

    @XmlElement
    public short getDuree() {
        return this.duree;
    }

    public void setDuree(short duree) {
        this.duree = duree;
    }

    public String toString() {
        Gson gson = new Gson();
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");

        HashMap<String, String> jsonArgs = new HashMap<String, String>();
        jsonArgs.put("creditId", Short.toString(getCreditId()));
        jsonArgs.put("compteEpargne", getCompteEpargne().toString());
        jsonArgs.put("montant", Float.toString(getMontant()));
        jsonArgs.put("taux", Short.toString(getTaux()));
        jsonArgs.put("dateEmprunt", df.format(getDateEmprunt()));
        jsonArgs.put("duree", Integer.toString(getDuree()));
        return gson.toJson(jsonArgs);
    }
}


