package banque.entity;
// Generated 27 mars 2016 14:02:36 by Hibernate Tools 4.3.1

import com.google.gson.Gson;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.HashMap;

/**
 * Personnel generated by hbm2java
 */
@XmlRootElement(name="personnel")
public class Personnel  implements java.io.Serializable {

     private Short personnelId;
     private Banque banque;
     private String nom;
     private String motdepasse;
     private String role;

    public Personnel() {
    }


    public Personnel(Banque banque, String nom) {
        this.banque = banque;
        this.nom = nom;
    }
    public Personnel(Banque banque, String nom, String motdepasse, String role) {
       this.banque = banque;
       this.nom = nom;
       this.motdepasse = motdepasse;
       this.role = role;
    }

    @XmlElement
    public Short getPersonnelId() {
        return this.personnelId;
    }

    public void setPersonnelId(Short personnelId) {
        this.personnelId = personnelId;
    }

    @XmlElement
    public Banque getBanque() {
        return this.banque;
    }

    public void setBanque(Banque banque) {
        this.banque = banque;
    }

    @XmlElement
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    @XmlElement
    public String getMotdepasse() {
        return this.motdepasse;
    }

    public void setMotdepasse(String motdepasse) {
        this.motdepasse = motdepasse;
    }

    @XmlElement
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String toString() {
        Gson gson = new Gson();
        HashMap<String, String> jsonArgs = new HashMap<String, String>();
        jsonArgs.put("personnelId", getPersonnelId().toString());
        jsonArgs.put("banque", getBanque().toString());
        jsonArgs.put("nom", getNom());
        jsonArgs.put("motdepasse", getMotdepasse());
        jsonArgs.put("role", getRole());
        return gson.toJson(jsonArgs);
    }
}


