///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package banque.frame;
//
//import banque.utils.HibernateUtil;
//import banque.entity.Banque;
//import banque.entity.ClientBanque;
//import java.util.List;
//import java.util.Vector;
//import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
//import org.hibernate.HibernateException;
//import org.hibernate.Query;
//import org.hibernate.Session;
//
///**
// *
// * @author pauline
// */
//public class FrameTest extends javax.swing.JFrame {
//
//    /**
//     * Creates new form FrameTest
//     */
//    public FrameTest() {
//        initComponents();
//    }
//
//    //Requete sur la base permettant de trouver une banque en fonction de son id
//    private static String QUERY_BASED_ON_ID = "from Banque b  where b.id =";
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    private void runQueryBasedOnId() {
//        executeHQLQuery(QUERY_BASED_ON_ID + numBanque.getText());
//    }
//
//    private void executeHQLQuery(String hql) {
//        try {
//            // Ouvrir une session puis commencer une transaction
//            Session session = HibernateUtil.getSessionFactory().openSession();
//            session.beginTransaction();
//            //Créer une nouvelle banque et un nouveau client
//            Banque bank = new Banque("bnp", "oleron");
//            ClientBanque clientB = new ClientBanque(bank, "devy", "colette","cdevy","colette@gmail.com","91360");
//            //Les sauvegarde dans la base
//            session.save(bank);
//            session.save(clientB);
//            //Executer la requete precedente
//            Query q = session.createQuery(hql);
//            List resultList = q.list();
//            //Afficher comme voulu
//            displayResult(resultList);
//            //Commit
//            session.getTransaction().commit();
//        } catch (HibernateException he) {
//            he.printStackTrace();
//        }
//    }
//
//    private void displayResult(List resultList) {
//
//        Vector<String> tableHeaders = new Vector<String>();
//        Vector tableData = new Vector();
//        tableHeaders.add("ClientId");
//        tableHeaders.add("Nom");
//        tableHeaders.add("Prenom");
//        tableHeaders.add("Mdp");
//
//        for (Object o : resultList) {
//            Banque banque = (Banque) o;
//            nomBanque.setText(banque.getNom());
//            villeBanque.setText(banque.getVille());
//
//            System.out.println(banque.getClientBanques().size());
//            for (Object ob : banque.getClientBanques()) {
//                ClientBanque client = (ClientBanque) ob;
//                Vector<Object> oneRow = new Vector<Object>();
//                oneRow.add(client.getClientBanqueId());
//                oneRow.add(client.getNom());
//                oneRow.add(client.getPrenom());
//                oneRow.add(client.getMotdepasse());
//                tableData.add(oneRow);
//            }
//
//        }
//        resultTable.setModel(new DefaultTableModel(tableData, tableHeaders));
//    }
//
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        jLabel1 = new javax.swing.JLabel();
//        numBanque = new javax.swing.JTextField();
//        query = new javax.swing.JButton();
//        nomBanque = new javax.swing.JLabel();
//        villeBanque = new javax.swing.JLabel();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        resultTable = new javax.swing.JTable();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jLabel1.setText("Numéro Banque :");
//
//        query.setText("Query");
//        query.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                queryActionPerformed(evt);
//            }
//        });
//
//        resultTable.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null}
//            },
//            new String [] {
//                "Title 1", "Title 2", "Title 3", "Title 4"
//            }
//        ));
//        jScrollPane1.setViewportView(resultTable);
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(nomBanque, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(38, 38, 38)
//                .addComponent(villeBanque, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(79, 79, 79))
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addGap(44, 44, 44)
//                .addComponent(jLabel1)
//                .addGap(18, 18, 18)
//                .addComponent(numBanque, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
//                .addComponent(query)
//                .addGap(34, 34, 34))
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
//                .addGap(22, 22, 22))
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addGap(50, 50, 50)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel1)
//                    .addComponent(numBanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(query))
//                .addGap(18, 18, 18)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(villeBanque, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(nomBanque, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(152, 152, 152))
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void queryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryActionPerformed
//        //Vide les champs texte
//        nomBanque.setText("");
//        villeBanque.setText("");
//        //Execue la requete que si le champs texte n'est pas vide
//        if (!numBanque.getText().equals("")) {
//            runQueryBasedOnId();
//        }
//
//    }//GEN-LAST:event_queryActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameTest().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JLabel nomBanque;
//    private javax.swing.JTextField numBanque;
//    private javax.swing.JButton query;
//    private javax.swing.JTable resultTable;
//    private javax.swing.JLabel villeBanque;
//    // End of variables declaration//GEN-END:variables
//}
