package Graphics;

import Metier.EchangeR;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import com.google.gson.reflect.TypeToken;
import java.awt.BorderLayout;
import java.util.HashMap;
import javax.swing.JComboBox;
import javax.swing.JPanel;
//import Metier.MethodesRest;

/**
 *
 * @author pauline
 */
public class EchangeArgent extends javax.swing.JPanel {

    //private MethodesRest con;
    private EchangeR con;
    private JComboBox cbDebit;
    private JComboBox cbCredit;
    /**
     * Creates new form EchangeArgent
     */
    public EchangeArgent() {
        con = new EchangeR();
        initComponents();
        initComboBox();
    }
    
    private void initComboBox(){
        Gson gson = new Gson();
        JPanel centre = new JPanel();
        centre.setLayout(new BorderLayout());
        String comptesCourant = con.getComptesCourant();
        JsonElement rootc = new JsonParser().parse(comptesCourant);
         HashMap<String, String> args = gson.fromJson(comptesCourant, new TypeToken<HashMap<String, String>>() {}.getType());
        //System.out.println(args.toString());     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
