package Graphics;

import java.awt.CardLayout;

/**
 *
 * @author pauline
 */
public class GererCompte extends javax.swing.JPanel {

    /**
     * Creates new form GererCompte
     */
    public GererCompte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consulterCompte = new javax.swing.JButton();
        consulterStatistiques = new javax.swing.JButton();
        creerClient = new javax.swing.JButton();
        ajoutPersonnel = new javax.swing.JButton();
        creerUnCompte = new javax.swing.JButton();
        echangeArgent = new javax.swing.JButton();

        consulterCompte.setText("Consulter un Compte");
        consulterCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterCompteActionPerformed(evt);
            }
        });

        consulterStatistiques.setText("Consulter les Statistiques");
        consulterStatistiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterStatistiquesActionPerformed(evt);
            }
        });

        creerClient.setText("Créer un Client");
        creerClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerClientActionPerformed(evt);
            }
        });

        ajoutPersonnel.setText("Ajouter un nouveau membre");
        ajoutPersonnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutPersonnelActionPerformed(evt);
            }
        });

        creerUnCompte.setText("Créer un Compte");
        creerUnCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerUnCompteActionPerformed(evt);
            }
        });

        echangeArgent.setText("Echange d'argent");
        echangeArgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                echangeArgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consulterStatistiques)
                    .addComponent(consulterCompte)
                    .addComponent(ajoutPersonnel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creerClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(creerUnCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(echangeArgent, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consulterCompte)
                .addGap(26, 26, 26)
                .addComponent(consulterStatistiques)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creerClient)
                    .addComponent(creerUnCompte))
                .addGap(26, 26, 26)
                .addComponent(echangeArgent)
                .addGap(30, 30, 30)
                .addComponent(ajoutPersonnel)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * Permet d'afficher le bon JPanel lors de l'appui sur "consulter un compte"
 * @param evt 
 */
    private void consulterCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterCompteActionPerformed
        //Montrer la carte consulter compte
        ((CardLayout) GlobalFrame.cards.getLayout()).show(GlobalFrame.cards, "paneConsulterCompte");
    }//GEN-LAST:event_consulterCompteActionPerformed
/**
 * Permet d'afficher le bon JPanel lors de l'appui sur "créer un client"
 * @param evt 
 */
    private void creerClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerClientActionPerformed
        // TODO add your handling code here:
        //Montrer la carte creer compte
        ((CardLayout) GlobalFrame.cards.getLayout()).show(GlobalFrame.cards, "paneCreerCompte");
    }//GEN-LAST:event_creerClientActionPerformed

/**
 * Permet d'afficher le bon JPanel lors de l'appui sur "ajouter un mebre du personnel"
 * @param evt 
 */
    private void ajoutPersonnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutPersonnelActionPerformed
        ((CardLayout) GlobalFrame.cards.getLayout()).show(GlobalFrame.cards, "paneAjoutPersonnel");

    }//GEN-LAST:event_ajoutPersonnelActionPerformed
/**
 * Permet d'afficher le bon JPanel lors de l'appui sur "créer un compte"
 * @param evt 
 */
    private void creerUnCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerUnCompteActionPerformed
        ((CardLayout) GlobalFrame.cards.getLayout()).show(GlobalFrame.cards, "paneCreerCompteClient");
    }//GEN-LAST:event_creerUnCompteActionPerformed
/**
 * Permet d'afficher le bon JPanel lors de l'appui sur "echange d'argent"
 * @param evt 
 */
    private void echangeArgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_echangeArgentActionPerformed
        String[] parts = GlobalFrame.idBanquePersonnel.getText().split(":");
System.out.println("id banque"+parts[1]);
        GlobalFrame.paneEchangeArgent.initComboBox(Integer.parseInt(parts[1]));
        ((CardLayout) GlobalFrame.cards.getLayout()).show(GlobalFrame.cards, "paneEchangeArgent");
        //GlobalFrame.cards.remove(paneEchangeArgent);

    }//GEN-LAST:event_echangeArgentActionPerformed
/**
 * Permet d'afficher le bon JPanel lors de l'appui sur "consulter les statistiques"
 * @param evt 
 */
    private void consulterStatistiquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterStatistiquesActionPerformed
        GlobalFrame.paneStats.initStats();
        ((CardLayout) GlobalFrame.cards.getLayout()).show(GlobalFrame.cards, "paneStats");
    }//GEN-LAST:event_consulterStatistiquesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ajoutPersonnel;
    private javax.swing.JButton consulterCompte;
    private javax.swing.JButton consulterStatistiques;
    private javax.swing.JButton creerClient;
    private javax.swing.JButton creerUnCompte;
    private javax.swing.JButton echangeArgent;
    // End of variables declaration//GEN-END:variables
}
